// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/relation/v1/relation.proto

package relation

import (
	v1 "github.com/bytedance-youthcamp-jbzx/tiktok/api/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================关注or取消关注===================================
type RelationActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// int64 user_id = 1; // 用户id
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                              // 用户鉴权token
	ToUserId      int64  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`     // 对方用户id
	ActionType    int32  `protobuf:"varint,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1-关注，2-取消关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationActionRequest) Reset() {
	*x = RelationActionRequest{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationActionRequest) ProtoMessage() {}

func (x *RelationActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationActionRequest.ProtoReflect.Descriptor instead.
func (*RelationActionRequest) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{0}
}

func (x *RelationActionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RelationActionRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *RelationActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type RelationActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationActionResponse) Reset() {
	*x = RelationActionResponse{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationActionResponse) ProtoMessage() {}

func (x *RelationActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationActionResponse.ProtoReflect.Descriptor instead.
func (*RelationActionResponse) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{1}
}

func (x *RelationActionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RelationActionResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// ==============================关注列表========================================
type RelationFollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // 用户鉴权token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationFollowListRequest) Reset() {
	*x = RelationFollowListRequest{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationFollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFollowListRequest) ProtoMessage() {}

func (x *RelationFollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFollowListRequest.ProtoReflect.Descriptor instead.
func (*RelationFollowListRequest) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{2}
}

func (x *RelationFollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RelationFollowListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RelationFollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	UserList      []*v1.User             `protobuf:"bytes,3,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`        // 用户信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationFollowListResponse) Reset() {
	*x = RelationFollowListResponse{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationFollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFollowListResponse) ProtoMessage() {}

func (x *RelationFollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFollowListResponse.ProtoReflect.Descriptor instead.
func (*RelationFollowListResponse) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{3}
}

func (x *RelationFollowListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RelationFollowListResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *RelationFollowListResponse) GetUserList() []*v1.User {
	if x != nil {
		return x.UserList
	}
	return nil
}

// ==============================粉丝列表=======================================
type RelationFollowerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // 用户鉴权token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationFollowerListRequest) Reset() {
	*x = RelationFollowerListRequest{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationFollowerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFollowerListRequest) ProtoMessage() {}

func (x *RelationFollowerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFollowerListRequest.ProtoReflect.Descriptor instead.
func (*RelationFollowerListRequest) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{4}
}

func (x *RelationFollowerListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RelationFollowerListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RelationFollowerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	UserList      []*v1.User             `protobuf:"bytes,3,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`        // 用户列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationFollowerListResponse) Reset() {
	*x = RelationFollowerListResponse{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationFollowerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFollowerListResponse) ProtoMessage() {}

func (x *RelationFollowerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFollowerListResponse.ProtoReflect.Descriptor instead.
func (*RelationFollowerListResponse) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{5}
}

func (x *RelationFollowerListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RelationFollowerListResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *RelationFollowerListResponse) GetUserList() []*v1.User {
	if x != nil {
		return x.UserList
	}
	return nil
}

// ==============================好友列表=======================================
type RelationFriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // 用户鉴权token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationFriendListRequest) Reset() {
	*x = RelationFriendListRequest{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFriendListRequest) ProtoMessage() {}

func (x *RelationFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFriendListRequest.ProtoReflect.Descriptor instead.
func (*RelationFriendListRequest) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{6}
}

func (x *RelationFriendListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RelationFriendListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RelationFriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	UserList      []*FriendUser          `protobuf:"bytes,3,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`        // 用户列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationFriendListResponse) Reset() {
	*x = RelationFriendListResponse{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationFriendListResponse) ProtoMessage() {}

func (x *RelationFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationFriendListResponse.ProtoReflect.Descriptor instead.
func (*RelationFriendListResponse) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{7}
}

func (x *RelationFriendListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RelationFriendListResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *RelationFriendListResponse) GetUserList() []*FriendUser {
	if x != nil {
		return x.UserList
	}
	return nil
}

type FriendUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                        // 和该好友的最新聊天消息
	MsgType         int64                  `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`                        // message消息的类型，0 => 当前请求用户接收的消息， 1 => 当前请求用户发送的消息
	Id              int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                                                 // 用户id
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                              // 用户名称
	FollowCount     int64                  `protobuf:"varint,5,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`            // 关注总数
	FollowerCount   int64                  `protobuf:"varint,6,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`      // 粉丝总数
	IsFollow        bool                   `protobuf:"varint,7,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`                     //true-已关注，false-未关注
	Avatar          string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`                                          // 用户头像
	BackgroundImage string                 `protobuf:"bytes,9,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"` // 用户个人页顶部大图
	Signature       string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`                                   // 个人简介
	TotalFavorited  int64                  `protobuf:"varint,11,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`  // 获赞数量
	WorkCount       int64                  `protobuf:"varint,12,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`                 // 作品数量
	FavoriteCount   int64                  `protobuf:"varint,13,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`     // 点赞数量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FriendUser) Reset() {
	*x = FriendUser{}
	mi := &file_api_relation_v1_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendUser) ProtoMessage() {}

func (x *FriendUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_relation_v1_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendUser.ProtoReflect.Descriptor instead.
func (*FriendUser) Descriptor() ([]byte, []int) {
	return file_api_relation_v1_relation_proto_rawDescGZIP(), []int{8}
}

func (x *FriendUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendUser) GetMsgType() int64 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *FriendUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FriendUser) GetFollowCount() int64 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *FriendUser) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *FriendUser) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *FriendUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendUser) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *FriendUser) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FriendUser) GetTotalFavorited() int64 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *FriendUser) GetWorkCount() int64 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *FriendUser) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

var File_api_relation_v1_relation_proto protoreflect.FileDescriptor

const file_api_relation_v1_relation_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/relation/v1/relation.proto\x12\vrelation.v1\x1a\x16api/user/v1/user.proto\"l\n" +
	"\x15RelationActionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\x05R\n" +
	"actionType\"X\n" +
	"\x16RelationActionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"J\n" +
	"\x19RelationFollowListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x88\x01\n" +
	"\x1aRelationFollowListResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12*\n" +
	"\tuser_list\x18\x03 \x03(\v2\r.user.v1.UserR\buserList\"L\n" +
	"\x1bRelationFollowerListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x8a\x01\n" +
	"\x1cRelationFollowerListResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12*\n" +
	"\tuser_list\x18\x03 \x03(\v2\r.user.v1.UserR\buserList\"J\n" +
	"\x19RelationFriendListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x92\x01\n" +
	"\x1aRelationFriendListResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x124\n" +
	"\tuser_list\x18\x03 \x03(\v2\x17.relation.v1.FriendUserR\buserList\"\x9c\x03\n" +
	"\n" +
	"FriendUser\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\x03R\amsgType\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\ffollow_count\x18\x05 \x01(\x03R\vfollowCount\x12%\n" +
	"\x0efollower_count\x18\x06 \x01(\x03R\rfollowerCount\x12\x1b\n" +
	"\tis_follow\x18\a \x01(\bR\bisFollow\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\t \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\tR\tsignature\x12'\n" +
	"\x0ftotal_favorited\x18\v \x01(\x03R\x0etotalFavorited\x12\x1d\n" +
	"\n" +
	"work_count\x18\f \x01(\x03R\tworkCount\x12%\n" +
	"\x0efavorite_count\x18\r \x01(\x03R\rfavoriteCount2\xa7\x03\n" +
	"\x0fRelationService\x12Y\n" +
	"\x0eRelationAction\x12\".relation.v1.RelationActionRequest\x1a#.relation.v1.RelationActionResponse\x12e\n" +
	"\x12RelationFollowList\x12&.relation.v1.RelationFollowListRequest\x1a'.relation.v1.RelationFollowListResponse\x12k\n" +
	"\x14RelationFollowerList\x12(.relation.v1.RelationFollowerListRequest\x1a).relation.v1.RelationFollowerListResponse\x12e\n" +
	"\x12RelationFriendList\x12&.relation.v1.RelationFriendListRequest\x1a'.relation.v1.RelationFriendListResponseBEZCgithub.com/bytedance-youthcamp-jbzx/tiktok/api/relation/v1;relationb\x06proto3"

var (
	file_api_relation_v1_relation_proto_rawDescOnce sync.Once
	file_api_relation_v1_relation_proto_rawDescData []byte
)

func file_api_relation_v1_relation_proto_rawDescGZIP() []byte {
	file_api_relation_v1_relation_proto_rawDescOnce.Do(func() {
		file_api_relation_v1_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_relation_v1_relation_proto_rawDesc), len(file_api_relation_v1_relation_proto_rawDesc)))
	})
	return file_api_relation_v1_relation_proto_rawDescData
}

var file_api_relation_v1_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_relation_v1_relation_proto_goTypes = []any{
	(*RelationActionRequest)(nil),        // 0: relation.v1.RelationActionRequest
	(*RelationActionResponse)(nil),       // 1: relation.v1.RelationActionResponse
	(*RelationFollowListRequest)(nil),    // 2: relation.v1.RelationFollowListRequest
	(*RelationFollowListResponse)(nil),   // 3: relation.v1.RelationFollowListResponse
	(*RelationFollowerListRequest)(nil),  // 4: relation.v1.RelationFollowerListRequest
	(*RelationFollowerListResponse)(nil), // 5: relation.v1.RelationFollowerListResponse
	(*RelationFriendListRequest)(nil),    // 6: relation.v1.RelationFriendListRequest
	(*RelationFriendListResponse)(nil),   // 7: relation.v1.RelationFriendListResponse
	(*FriendUser)(nil),                   // 8: relation.v1.FriendUser
	(*v1.User)(nil),                      // 9: user.v1.User
}
var file_api_relation_v1_relation_proto_depIdxs = []int32{
	9, // 0: relation.v1.RelationFollowListResponse.user_list:type_name -> user.v1.User
	9, // 1: relation.v1.RelationFollowerListResponse.user_list:type_name -> user.v1.User
	8, // 2: relation.v1.RelationFriendListResponse.user_list:type_name -> relation.v1.FriendUser
	0, // 3: relation.v1.RelationService.RelationAction:input_type -> relation.v1.RelationActionRequest
	2, // 4: relation.v1.RelationService.RelationFollowList:input_type -> relation.v1.RelationFollowListRequest
	4, // 5: relation.v1.RelationService.RelationFollowerList:input_type -> relation.v1.RelationFollowerListRequest
	6, // 6: relation.v1.RelationService.RelationFriendList:input_type -> relation.v1.RelationFriendListRequest
	1, // 7: relation.v1.RelationService.RelationAction:output_type -> relation.v1.RelationActionResponse
	3, // 8: relation.v1.RelationService.RelationFollowList:output_type -> relation.v1.RelationFollowListResponse
	5, // 9: relation.v1.RelationService.RelationFollowerList:output_type -> relation.v1.RelationFollowerListResponse
	7, // 10: relation.v1.RelationService.RelationFriendList:output_type -> relation.v1.RelationFriendListResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_relation_v1_relation_proto_init() }
func file_api_relation_v1_relation_proto_init() {
	if File_api_relation_v1_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_relation_v1_relation_proto_rawDesc), len(file_api_relation_v1_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_relation_v1_relation_proto_goTypes,
		DependencyIndexes: file_api_relation_v1_relation_proto_depIdxs,
		MessageInfos:      file_api_relation_v1_relation_proto_msgTypes,
	}.Build()
	File_api_relation_v1_relation_proto = out.File
	file_api_relation_v1_relation_proto_goTypes = nil
	file_api_relation_v1_relation_proto_depIdxs = nil
}
