// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/favorite/v1/favorite.proto

package favorite

import (
	v1 "github.com/bytedance-youthcamp-jbzx/tiktok/api/video/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===========================点赞or取消点赞====================================
type FavoriteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户id
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                              // 用户鉴权token
	VideoId       int64                  `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`          // 视频id
	ActionType    int32                  `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1-点赞，2-取消点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionRequest) Reset() {
	*x = FavoriteActionRequest{}
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionRequest) ProtoMessage() {}

func (x *FavoriteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionRequest.ProtoReflect.Descriptor instead.
func (*FavoriteActionRequest) Descriptor() ([]byte, []int) {
	return file_api_favorite_v1_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteActionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteActionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FavoriteActionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *FavoriteActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type FavoriteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionResponse) Reset() {
	*x = FavoriteActionResponse{}
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionResponse) ProtoMessage() {}

func (x *FavoriteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionResponse.ProtoReflect.Descriptor instead.
func (*FavoriteActionResponse) Descriptor() ([]byte, []int) {
	return file_api_favorite_v1_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteActionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FavoriteActionResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

// ==============================点赞列表=======================================
type FavoriteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                  // 用户鉴权token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListRequest) Reset() {
	*x = FavoriteListRequest{}
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListRequest) ProtoMessage() {}

func (x *FavoriteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListRequest.ProtoReflect.Descriptor instead.
func (*FavoriteListRequest) Descriptor() ([]byte, []int) {
	return file_api_favorite_v1_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *FavoriteListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type FavoriteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 状态码，0-成功，其他值-失败
	StatusMsg     string                 `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`     // 返回状态描述
	VideoList     []*v1.Video            `protobuf:"bytes,3,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`     // 用户点赞视频列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteListResponse) Reset() {
	*x = FavoriteListResponse{}
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteListResponse) ProtoMessage() {}

func (x *FavoriteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favorite_v1_favorite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteListResponse.ProtoReflect.Descriptor instead.
func (*FavoriteListResponse) Descriptor() ([]byte, []int) {
	return file_api_favorite_v1_favorite_proto_rawDescGZIP(), []int{3}
}

func (x *FavoriteListResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FavoriteListResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *FavoriteListResponse) GetVideoList() []*v1.Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

var File_api_favorite_v1_favorite_proto protoreflect.FileDescriptor

const file_api_favorite_v1_favorite_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/favorite/v1/favorite.proto\x12\vfavorite.v1\x1a\x18api/video/v1/video.proto\"\x82\x01\n" +
	"\x15FavoriteActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\x05R\n" +
	"actionType\"X\n" +
	"\x16FavoriteActionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\"D\n" +
	"\x13FavoriteListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x86\x01\n" +
	"\x14FavoriteListResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x02 \x01(\tR\tstatusMsg\x12.\n" +
	"\n" +
	"video_list\x18\x03 \x03(\v2\x0f.video.v1.VideoR\tvideoList2\xc1\x01\n" +
	"\x0fFavoriteService\x12Y\n" +
	"\x0eFavoriteAction\x12\".favorite.v1.FavoriteActionRequest\x1a#.favorite.v1.FavoriteActionResponse\x12S\n" +
	"\fFavoriteList\x12 .favorite.v1.FavoriteListRequest\x1a!.favorite.v1.FavoriteListResponseBEZCgithub.com/bytedance-youthcamp-jbzx/tiktok/api/favorite/v1;favoriteb\x06proto3"

var (
	file_api_favorite_v1_favorite_proto_rawDescOnce sync.Once
	file_api_favorite_v1_favorite_proto_rawDescData []byte
)

func file_api_favorite_v1_favorite_proto_rawDescGZIP() []byte {
	file_api_favorite_v1_favorite_proto_rawDescOnce.Do(func() {
		file_api_favorite_v1_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_favorite_v1_favorite_proto_rawDesc), len(file_api_favorite_v1_favorite_proto_rawDesc)))
	})
	return file_api_favorite_v1_favorite_proto_rawDescData
}

var file_api_favorite_v1_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_favorite_v1_favorite_proto_goTypes = []any{
	(*FavoriteActionRequest)(nil),  // 0: favorite.v1.FavoriteActionRequest
	(*FavoriteActionResponse)(nil), // 1: favorite.v1.FavoriteActionResponse
	(*FavoriteListRequest)(nil),    // 2: favorite.v1.FavoriteListRequest
	(*FavoriteListResponse)(nil),   // 3: favorite.v1.FavoriteListResponse
	(*v1.Video)(nil),               // 4: video.v1.Video
}
var file_api_favorite_v1_favorite_proto_depIdxs = []int32{
	4, // 0: favorite.v1.FavoriteListResponse.video_list:type_name -> video.v1.Video
	0, // 1: favorite.v1.FavoriteService.FavoriteAction:input_type -> favorite.v1.FavoriteActionRequest
	2, // 2: favorite.v1.FavoriteService.FavoriteList:input_type -> favorite.v1.FavoriteListRequest
	1, // 3: favorite.v1.FavoriteService.FavoriteAction:output_type -> favorite.v1.FavoriteActionResponse
	3, // 4: favorite.v1.FavoriteService.FavoriteList:output_type -> favorite.v1.FavoriteListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_favorite_v1_favorite_proto_init() }
func file_api_favorite_v1_favorite_proto_init() {
	if File_api_favorite_v1_favorite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_favorite_v1_favorite_proto_rawDesc), len(file_api_favorite_v1_favorite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_favorite_v1_favorite_proto_goTypes,
		DependencyIndexes: file_api_favorite_v1_favorite_proto_depIdxs,
		MessageInfos:      file_api_favorite_v1_favorite_proto_msgTypes,
	}.Build()
	File_api_favorite_v1_favorite_proto = out.File
	file_api_favorite_v1_favorite_proto_goTypes = nil
	file_api_favorite_v1_favorite_proto_depIdxs = nil
}
